name: Compliance Rules Checks

on:
  push

jobs:
  docker-benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test_name: legacy
            policy_tag: v0.17
            dist_channel: stable
          - test_name: rego
            policy_tag: v0.18.6
            dist_channel: beta
    steps:
      - name: Checkout current code
        uses: actions/checkout@v2

      - name: Checkout test code
        uses: actions/checkout@v2
        with:
          repository: DataDog/security-agent-policies
          ref: ${{ matrix.policy_tag }}
          path: tests

      - name: Setup Auditd and Docker compliance
        run: ./testdata/setup_compliance.sh
      
      - name: Setup Datadog Agent
        env:
          DD_API_KEY: faketemp
          DD_AGENT_MAJOR_VERSION: 7
          DD_SITE: datadoghq.com
          REPO_URL: datad0g.com
          DD_AGENT_DIST_CHANNEL: ${{ matrix.dist_channel }}
        run: |
          bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"

      - name: Run checks
        run: |
          sudo /opt/datadog-agent/embedded/bin/security-agent compliance check --file ${{ github.workspace }}/tests/compliance/containers/cis-docker-1.2.0.yaml > results.txt

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
            name: docker-benchmark-results-${{ matrix.test_name }}
            path: results.txt


  results-comparison:
    runs-on: ubuntu-latest
    needs: docker-benchmark
    steps:
      - uses: actions/download-artifact@v2

      - name: Compare
        run: |
          cat docker-benchmark-results-legacy/results.txt
          cat docker-benchmark-results-rego/results.txt
